.TH ANKIADDERALL "1" "2023\-04\-04" "AnkiAdderAll" "Generated Python Manual"
.SH NAME
Ankiadderall
.SH SYNOPSIS
.B Ankiadderall
[-h] [-D DECK] [-t CARDTYPE] [-i IP] [-p PORT] [-f [FILE ...]] [-c CONFIG] [--alias ALIAS] [-F IFS] [--column [COLUMN]] [--debug] [cardContents]
.SH DESCRIPTION
a command line application to create anki cards

.TP
\fBcardContents\fR
a positional contents of a card

.SH OPTIONS
.TP
\fB\-D\fR \fI\,DECK\/\fR, \fB\-\-deck\fR \fI\,DECK\/\fR
set a Deck.

.TP
\fB\-t\fR \fI\,CARDTYPE\/\fR, \fB\-\-type\fR \fI\,CARDTYPE\/\fR
set a card type.

.TP
\fB\-i\fR \fI\,IP\/\fR, \fB\-\-ip\fR \fI\,IP\/\fR
set a AnkiConnect ip.

.TP
\fB\-p\fR \fI\,PORT\/\fR, \fB\-\-port\fR \fI\,PORT\/\fR
set a AnkiConnect port.

.TP
\fB\-f\fR \fI\,[FILE ...]\/\fR, \fB\-\-file\fR \fI\,[FILE ...]\/\fR
set a file to create cards.

.TP
\fB\-c\fR \fI\,CONFIG\/\fR, \fB\-\-config\fR \fI\,CONFIG\/\fR
set a config.

.TP
\fB\-\-alias\fR \fI\,ALIAS\/\fR
set an alias.

.TP
\fB\-F\fR \fI\,IFS\/\fR, \fB\-\-IFS\fR \fI\,IFS\/\fR
a sed\-like IFS option

.TP
\fB\-\-column\fR \fI\,[COLUMN]\/\fR
a positional contents of a card

.TP
\fB\-\-debug\fR
a debug option

.SH COMMENTS
Constantin Hong

.SH AUTHORS
.nf
Constantin Hong --author-email hongconstantin@gmail.com
.fi
